### ISSUE TITLE
Issue after updating to setup-solana 1.2, 1.0 was fine.

### ISSUE THREAD

**Issue by mikemaccana** [metaDAOproject/setup-solana#8]
I was previously using:

```yaml
      - uses: metadaoproject/setup-solana@v1.0
        with:
          # Install Solana CLI (beta, required to fix 'ahash' issue)
          solana-cli-version: "1.18.5"
```

Updated to:

```yaml       
      - uses: metadaoproject/setup-solana@v1.2
```    

Which returns: 

```
Run chmod +x scripts/channel-info.sh
  chmod +x scripts/channel-info.sh
  output=$("scripts/channel-info.sh")
  read -r BETA_CHANNEL_LATEST_TAG STABLE_CHANNEL_LATEST_TAG <<< "$output"
  
  if [[ "stable" =~ ^[a-zA-Z] ]]; then
    if [[ stable =~ ^(edge|stable|beta)$ ]]; then
      if [[ stable == "edge" ]]; then
        echo "Using Solana CLI edge channel"
        echo "install_version=edge" >> $GITHUB_OUTPUT
      elif [[ stable == "stable" ]]; then
        echo "Using Solana CLI stable channel $install_version"
        echo "install_version=$STABLE_CHANNEL_LATEST_TAG" >> $GITHUB_OUTPUT
      elif [[ stable == "beta" ]]; then
        echo "Using Solana CLI beta channel"
        echo "install_version=$BETA_CHANNEL_LATEST_TAG" >> $GITHUB_OUTPUT
      fi
    else
      echo "Invalid Solana CLI channel: stable"
      exit 1
    fi
  else
    echo "Using Solana CLI stable"
    echo "install_version=vstable" >> $GITHUB_OUTPUT
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
chmod: cannot access 'scripts/channel-info.sh': No such file or directory
```
